#!/bin/bash
#CETIN Milan Sykora - check pro statistiky knot dns
#

stats=/var/lib/knot/stats/stats.yaml

if [ -f "$stats" ]
   then
     echo "<<<knot_dns>>>"
   else
     echo "soubor statistik neexistuje"
     exit
fi




for STATISTIKA in `cat $stats | sed 's/^ *//'`
do
        if [[ "$STATISTIKA" == "query-type:" ]]
        then
                UPRAVA=`cat $stats | sed -e '1,/query-type:/d' -e '//,$d' | sed 's/^ *//'`
                echo -e "query-type:"
                echo -e "$UPRAVA"
        fi
done

for STATISTIKA in `cat $stats | sed 's/^ *//'`
do

        if [[ "$STATISTIKA" == "response-code:" ]]
        then
                UPRAVA=`cat $stats | sed -e '1,/response-code:/d' -e '/reply-nodata:/,$d' | sed 's/^ *//'`
                echo -e "response-code:"
                echo -e "$UPRAVA"
        fi
done

